name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t $DOCKER_USERNAME/auto_pipe .
        docker push $DOCKER_USERNAME/auto_pipe

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1.1.1
      with:
        service_account_key: ${{ secrets.GCP_KEY_FILE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: ${{ secrets.GCP_REGION }}

    - name: Deploy to GCP Cloud Run
      run: |
        gcloud run deploy auto-pipe \
          --image $DOCKER_USERNAME/auto_pipe \
          --platform managed \
          --region ${{ secrets.GCP_REGION }}
