name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/auto_pipe:latest
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: auto-pipe
        image: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/auto_pipe:latest
        project: ${{ secrets.GCP_PROJECT_ID }}
        region: ${{ secrets.GCP_REGION }}
        credentials: ${{ secrets.GCP_KEY_FILE }}
