name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t $DOCKER_USERNAME/auto_pipe .
        docker push $DOCKER_USERNAME/auto_pipe

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
     
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GCP_PRIVATE_KEY }}

    - name: gcp deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.GCP_PORT }} ${{ secrets.GCP_USER }}@${{ secrets.EX_IP }} 'bash -s' << 'EOF'
          docker stop api-app
          docker pull rlanman/api-project
          docker run -d --rm --name api-app -p 80:4000 --network my-network rlanman/api-project
        EOF
