name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_KEY_FILE }}
        export_default_credentials: true

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        docker buildx create --use
        docker buildx inspect default --bootstrap

        docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/auto_pipe:latest -t $DOCKER_USERNAME/auto_pipe:v1 .
        docker push $DOCKER_USERNAME/auto_pipe
